### PR TITLE
feat: support option for having only `semantic` classes

### LINKED ISSUE #14: Option to have only semantic classes
One thing the I like the most about radix ui colors is the ability to have enough flexibility using only the semantic meaning as stated in https://www.radix-ui.com/colors/docs/palette-composition/understanding-the-scale

It think a good addition is having an option to disable the access to the low level color/step.

```diff
declare interface TailwindCSSRadixColorsOptions {
    /**
     * Disable the semantics classes, such as `bg-red-solid`.
     * 
+    * @deprecated Use `class: "step"` instead
     */
    disableSemantics?: boolean;

    /**
    * Choose which class `bg-red-solid`.
    * 
    * @default 'both'
    */
+   class?: "semantic" | "step" | "both";
}
```

Without releasing a major, `disableSemantics` when used sets `class` to `step`, but having `class` precedence.

If you are interested I can take a look and try to make a PR.

### PR DESCRIPTION
**Pull request by f15u**
Fix #14.

### CODE REVIEW

**Comment by f15u** [comment]
At the moment I'm blocked because of what I think is a TailwindCSS limitation. Adding colors to the default configuration, Tailwind generates all the utilities associated with them.

This makes impossible to exclude the `style: "steps"` classes.

I tried removing the `colors` from the default configuration, but this would increase the plugin complexity because we should generate all other color based utilities (border, bg, etc) by ourself.

At the moment I have no other ideas on how to implement this.

The initial issue was raised because of performance problems with the VSCode extension probably due to the 31*12 (*372*) colors added to the default palette.
Maybe can we mitigate this problem adding the ability to choose **which** colors the plugin should add instead of all of them?

**Comment by mrcaidev** [comment]
Yes. Step classes and semantic classes are generated with different approaches, i.e. config extension and `addComponents` respectively. So it may need some foundamental changes to implement this feature.

The option you suggested makes sense to me. Maybe add an option called `palette` or `colors`, which defaults to all Radix colors if not passed in. Or if users want to enhance IDE proficiency, they can specify desired colors (with their steps always enabled, and their semantics enabled by default but configurable via `disableSemantics`).

Tell me if you are going to implement this in this PR, or any other suggestion!

**Comment by f15u** [comment]
> [...] Tell me if you are going to implement this in this PR, or any other suggestion!

I think we can keep this as draft. I'll open another PR where I try to implement the `palette`/`colors` option.

Maybe something will change with the release of Tailwind v4 and this could be implemented.

**Comment by mrcaidev** [comment]
In `v1.3.0` we have `include` and `exclude` option, which lets you decide which colors to be included (in intellisense).

They work like the `include` and `exclude` in tsconfig, and hence the name.

Just want to make sure you don't have to implement them from scratch, as they have been realized already. But suggestions and PRs are always welcomed!

**Comment by f15u** [comment]
> [...] Just want to make sure you don't have to implement them from scratch, as they have been realized already. But suggestions and PRs are always welcomed!

I think I can close this one then. Thank you for adding them :pray:

**Pull request closed without merging**
